version: '3'
services:
  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: ${INTEGRATION_TEST_TIMEOUT}

  myservice:
    image: myservice

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"

  consul:
    image: progrium/consul
    ports:
      - "8500"
    command: "-client 0.0.0.0 -config-dir /tmp"

  thread-exception:
    image: thread-exception
    volumes:
      - ../..:/usr/local/src/xivo-lib-python:ro
